# Generated by Django 3.1.7 on 2021-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quality',
        ),
        migrations.AddField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
