# Generated by Django 3.1.7 on 2021-03-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0002_auto_20210310_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommpage.shippingaddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='2213715335', max_length=10, null=True),
        ),
    ]
