# Generated by Django 3.1.7 on 2021-03-06 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecommpage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommpage', '0002_auto_20210305_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to=ecommpage.models.get_upload_path),
        ),
        migrations.CreateModel(
            name='OrderComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommpage.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
