# Generated by Django 3.1.7 on 2021-03-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0003_auto_20210311_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='6492993590', max_length=10, null=True),
        ),
    ]
