# Generated by Django 3.1.7 on 2021-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0003_auto_20210309_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='6158927852', max_length=10, null=True),
        ),
    ]
