# Generated by Django 3.1.7 on 2021-03-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0004_auto_20210309_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mode_of_payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='3970574196', max_length=10, null=True),
        ),
    ]
