# Generated by Django 3.1.7 on 2021-03-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0004_auto_20210307_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
