# Generated by Django 3.1.7 on 2021-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0005_auto_20210311_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='6098084423', max_length=10, null=True),
        ),
    ]
