# Generated by Django 3.1.7 on 2021-03-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0007_auto_20210303_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
