# Generated by Django 3.1.7 on 2021-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0008_auto_20210311_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='1034653180', max_length=10, null=True, unique=True),
        ),
    ]
