# Generated by Django 3.1.7 on 2021-03-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommpage', '0010_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='creator',
        ),
    ]
