# Generated by Django 3.1.7 on 2021-03-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='provice',
            new_name='province',
        ),
    ]
