# Generated by Django 3.1.7 on 2021-03-06 13:35

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210305_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to=account.models.get_upload_path),
        ),
    ]
