# Generated by Django 3.1.7 on 2021-03-11 11:20

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210311_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to=account.models.get_upload_path),
        ),
    ]
